### ISSUE TITLE
Possible for deployed walletsplitter contract to withdraw funds from another contract?

### ISSUE THREAD

**Issue by btroia** [Wallet-Splitter/wallet-splitter#2]
Hi, thanks for making this tool. Is it possible for a walletsplitter contract to automatically withdraw funds from another contract where it is the only recipient?

For example, let's say there is an NFT contract (ERC721A, etc.) that receives payments. Best practice is to have recipients _pull_ payments from the contract vs. pushing payments.

Recipients can pull their payments from the _walletsplitter_ contract itself, but is there a way for the walletsplitter contract to automatically pull payments from the main NFT contract?

```
NFT contract (receives payments)
    |--> (pull) Walletsplitter pulls payments to contract wallet
         |--> (pull) Alice's pulls walletsplitter payments split to Alice's wallet
         |--> (pull) Bob pulls walletsplitter payments split to Bob's wallet
```

Thanks in advance for any help!

**Comment by leon-do** [comment]
sorry for the very late reply. This might be possible but will require modification to Open Zepplin's smart contract. 

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v4.4/contracts/finance/PaymentSplitter.sol
